"""create horario table with FKs

Revision ID: a0edf2b872ef
Revises: 965fd79ba538
Create Date: 2025-05-11 16:44:03.852766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0edf2b872ef'
down_revision: Union[str, None] = '965fd79ba538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('sala', sa.Integer(), nullable=False),
    sa.Column('curso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso'], ['curso.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sala'], ['sala.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horario')
    # ### end Alembic commands ###
