"""create alumno_curso table with FKs

Revision ID: c895313322de
Revises: 4b7f4ecfe114
Create Date: 2025-05-11 16:43:22.665388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c895313322de'
down_revision: Union[str, None] = '4b7f4ecfe114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumno_curso',
    sa.Column('alumno', sa.Integer(), nullable=False),
    sa.Column('curso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['curso'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('alumno', 'curso')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumno_curso')
    # ### end Alembic commands ###
